version: '3'

service:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTEGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid